language: ruby
rvm:
  - 2.3.0
  - 2.5.0

notifications:
  email: false

env:
  global:
    - CC_TEST_REPORTER_ID=4f71f6b01a6f60210b2295b71ba83750eeea15e62362ca4428982b0312359b5e
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
